on: [push]

name: Build head

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - run: strip target/release/vault-hunter

      - uses: actions/upload-artifact@v2
        with:
          name: vault-hunter-linux
          path: target/release/vault-hunter

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@v2
        with:
          name: vault-hunter-windows
          path: target/release/vault-hunter.exe

  build-mac:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - run: strip target/release/vault-hunter

      - uses: actions/upload-artifact@v2
        with:
          name: vault-hunter-mac
          path: target/release/vault-hunter
